name: CI - Build & Test Spring Boot

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install MySQL (Manual)
        run: |
          sudo apt update
          sudo apt install -y mysql-server
          sudo systemctl start mysql
          sudo mysql -e "CREATE DATABASE webtourism;"
          sudo mysql -e "CREATE USER 'ci_user'@'localhost' IDENTIFIED BY 'password';"
          sudo mysql -e "GRANT ALL PRIVILEGES ON webtourism.* TO 'ci_user'@'localhost';"
          sudo mysql -e "FLUSH PRIVILEGES;"

      - name: Verify MySQL
        run: mysql -u ci_user -ppassword -e "SHOW DATABASES;"

      - name: Run Tests
        run: mvn test
