name: CI - Build & Test Spring Boot

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_DATABASE: webtourism
          MYSQL_USER: root
          MYSQL_PASSWORD: luanml001
          MYSQL_ROOT_PASSWORD: luanml001
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -u root -pluanml001"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Wait for MySQL to be ready
        run: sleep 30  # Chờ MySQL khởi động

      - name: Run Tests
        run: mvn test
