name: CI - Build & Test Spring Boot

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install MySQL (No Password)
        run: |
          sudo apt update
          sudo apt install -y mysql-server
          sudo systemctl start mysql
          sudo systemctl status mysql

      - name: Create Test Database
        run: |
          sudo mysql -e "CREATE DATABASE webtourism;"
          sudo mysql -e "SHOW DATABASES;"

      - name: Run Tests
        run: mvn test
