name: CI - Build & Test Spring Boot

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Cài đặt MySQL trên GitHub Actions (KHÔNG DÙNG DOCKER)
      - name: Install MySQL
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server
          sudo systemctl start mysql

      # Thiết lập user & database MySQL giống trên máy bạn
      - name: Setup MySQL Database
        run: |
          mysql -e "CREATE DATABASE IF NOT EXISTS webtourism;"
          mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'luanml001';"
          mysql -e "FLUSH PRIVILEGES;"

      # Kiểm tra MySQL có hoạt động không
      - name: Verify MySQL Connection
        run: mysql -u root -pluanml001 -e "SHOW DATABASES;"

      # Chạy test
      - name: Run Tests
        run: mvn test
