name: CI - Build & Test Spring Boot

on:
  push:
    branches:
      - main  # Chạy CI khi có code mới trên nhánh main
    # paths:
          # - 'src/**'   # Chỉ chạy khi có thay đổi trong thư mục src/

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-

      - name: Build & Run Tests
        run: mvn clean package test
